version: "3.7"

services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env.local
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: travelbuddy_api
    env_file:
      - .env.local
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    command: npm run start

volumes:
  postgres_db_data:
