version: "3.7"

services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql_db
    env_file:
      - .env.local
    volumes:
      - mysql_db_data:/var/lib/mysql/data
    restart: always
    ports:
      - "3306:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: travelbuddy_api
    env_file:
      - .env.local
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    command: npm run start

volumes:
  mysql_db_data:
