name: Deploy Node JS application on EC2

on:
  push:
    branches:
      - main
      - feat/staging-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the docker image
        run: docker build --platform=linux/amd64 -t garvitmaloo21/travelbuddy-api:latest .

      - name: Push image to docker hub
        run: docker push garvitmaloo21/travelbuddy-api:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull garvitmaloo21/travelbuddy-api:latest

      - name: Remove existing container
        run: docker stop travelbuddy-api && docker rm -f travelbuddy-api

      - name: Start a new container
        run: docker run --name travelbuddy-api -d -p 9000:9000 -e DB_HOST=${{ secrets.DB_HOST }} -e DB_PORT=${{ secrets.DB_PORT }} -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_NAME=${{ secrets.DB_NAME }} garvitmaloo21/travelbuddy-api:latest
